### ISSUE TITLE
The mapping registration should be moved outside ObjectStore

### ISSUE THREAD

**Issue by alexguzun** [vlingo/vlingo-symbio#15]
Curently the `ObjectStore` protocol defines a method used to register mapping for a given persistent type.
```
void registerMapper(final PersistentObjectMapper mapper);
```
Most of the stores simply proxy the call to their persistent delegates and do nothing more. 
With the introduction of `io.vlingo.symbio.store.dispatch.Dispatchable` the store has to have the mapping for it. Also a copy of the store delegate is usually used by `DispatcherControlActor` actor.  More details in this discussion: https://github.com/vlingo/vlingo-symbio-jdbc/pull/14#discussion_r301147391

It makes more sense to register the mapping directly with the persistent delegate. 
The idea is to create an interface, for example `ObjectStoreDelegate` that defines the `registerMapper` implementation.
 
This will allow the clients to register all the necessary mappings, including the one for `io.vlingo.symbio.store.dispatch.Dispatchable` before creating the actor. 

With the new Object store delegate interface, the following projects must also be changed:
- https://github.com/vlingo/vlingo-symbio-geode
- https://github.com/vlingo/vlingo-symbio-jdbc
- https://github.com/vlingo/vlingo-lattice (mostly tests)

**Comment by VaughnVernon** [comment]
@alexguzun I like it. When you are ready, please implement this.

**Comment by alexguzun** [comment]
Fixed by https://github.com/vlingo/vlingo-symbio/pull/16
